body {
  background-color: #4B7399;
  font-family: Verdana, Helvetica, Arial;
  font-size: 12px;
}

a img {
  border: none;
}

a {
  color: #0000FF;
}

.clear {
  clear: both;
  height: 0;
  overflow: hidden;
}

#container {
  width: 75%;
  margin: 0 auto;
  background-color: #FFF;
  padding: 20px 40px;
  border: solid 1px black;
  margin-top: 20px;
}

#flash_notice, #flash_error, #flash_alert {
  padding: 5px 8px;
  margin: 10px 0;
}

#flash_notice {
  background-color: #CFC;
  border: solid 1px #6C6;
}

#flash_error, #flash_alert {
  background-color: #FCC;
  border: solid 1px #C66;
}

.fieldWithErrors {
  display: inline;
}

.error_messages {
  width: 400px;
  border: 2px solid #CF0000;
  padding: 0px;
  padding-bottom: 12px;
  margin-bottom: 20px;
  background-color: #f0f0f0;
  font-size: 12px;
}

.error_messages h2 {
  text-align: left;
  font-weight: bold;
  padding: 5px 10px;
  font-size: 12px;
  margin: 0;
  background-color: #c00;
  color: #fff;
}

.error_messages p {
  margin: 8px 10px;
}

.error_messages ul {
  margin: 0;
}


/* Tabelas */

table, td{
	font:100% Arial, Helvetica, sans-serif; 
}
table{width:90%;border-collapse:collapse;margin:1em 0; margin-left: 30px;}
th, td{text-align:left;padding:.5em;border:1px solid #fff;}
th{background:#328aa4 url(tr_back.gif) repeat-x;color:#fff;}
td{background:#e5f1f4;}

/* tablecloth styles */

tr.even td{background:#e5f1f4;}
tr.odd td{background:#f8fbfc;}

th.over, tr.even th.over, tr.odd th.over{background:#4a98af;}
th.down, tr.even th.down, tr.odd th.down{background:#bce774;}
th.selected, tr.even th.selected, tr.odd th.selected{}

td.over, tr.even td.over, tr.odd td.over{background:#ecfbd4;}
td.down, tr.even td.down, tr.odd td.down{background:#bce774;color:#fff;}
td.selected, tr.even td.selected, tr.odd td.selected{background:#bce774;color:#555;}

/* use this if you want to apply different styleing to empty table cells*/
td.empty, tr.odd td.empty, tr.even td.empty{background:#fff;}


/* Formulários */

input, textarea, select { font-size:100%; padding:5px; -moz-box-shadow:0 0 10px #EEEEEE inset;border:1px solid #CCCCCC;-moz-border-radius:2px;padding:8px;background-color:#FFF; text-align: left;}

textarea { width:400px; height: 110px; font-size:100%; padding:5px; -moz-box-shadow:0 0 10px #EEEEEE inset;border:1px solid #CCCCCC;-moz-border-radius:2px;padding:8px;background-color:#FFF; text-align: left;}

img {border:4px solid #005AAB;margin:5px;display:inline}


/* Listas */

ul 
{ 
    list-style-type: cicle; 
} 
ul li{ 
    padding: 0px 0px; 
    color: #000333; 
} 
ol 
{ 
    list-style-type: decimal-numeração; 
} 
ol li{ 
    color: #666666; 
    font-family: Arial, Helvetica, sans-serif;
    font-size: 26px;
}
