require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MetodoDePagamentosController do

  def mock_metodo_de_pagamento(stubs={})
    @mock_metodo_de_pagamento ||= mock_model(MetodoDePagamento, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all metodo_de_pagamentos as @metodo_de_pagamentos" do
      MetodoDePagamento.stub(:all) { [mock_metodo_de_pagamento] }
      get :index
      assigns(:metodo_de_pagamentos).should eq([mock_metodo_de_pagamento])
    end
  end

  describe "GET show" do
    it "assigns the requested metodo_de_pagamento as @metodo_de_pagamento" do
      MetodoDePagamento.stub(:find).with("37") { mock_metodo_de_pagamento }
      get :show, :id => "37"
      assigns(:metodo_de_pagamento).should be(mock_metodo_de_pagamento)
    end
  end

  describe "GET new" do
    it "assigns a new metodo_de_pagamento as @metodo_de_pagamento" do
      MetodoDePagamento.stub(:new) { mock_metodo_de_pagamento }
      get :new
      assigns(:metodo_de_pagamento).should be(mock_metodo_de_pagamento)
    end
  end

  describe "GET edit" do
    it "assigns the requested metodo_de_pagamento as @metodo_de_pagamento" do
      MetodoDePagamento.stub(:find).with("37") { mock_metodo_de_pagamento }
      get :edit, :id => "37"
      assigns(:metodo_de_pagamento).should be(mock_metodo_de_pagamento)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created metodo_de_pagamento as @metodo_de_pagamento" do
        MetodoDePagamento.stub(:new).with({'these' => 'params'}) { mock_metodo_de_pagamento(:save => true) }
        post :create, :metodo_de_pagamento => {'these' => 'params'}
        assigns(:metodo_de_pagamento).should be(mock_metodo_de_pagamento)
      end

      it "redirects to the created metodo_de_pagamento" do
        MetodoDePagamento.stub(:new) { mock_metodo_de_pagamento(:save => true) }
        post :create, :metodo_de_pagamento => {}
        response.should redirect_to(metodo_de_pagamento_url(mock_metodo_de_pagamento))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved metodo_de_pagamento as @metodo_de_pagamento" do
        MetodoDePagamento.stub(:new).with({'these' => 'params'}) { mock_metodo_de_pagamento(:save => false) }
        post :create, :metodo_de_pagamento => {'these' => 'params'}
        assigns(:metodo_de_pagamento).should be(mock_metodo_de_pagamento)
      end

      it "re-renders the 'new' template" do
        MetodoDePagamento.stub(:new) { mock_metodo_de_pagamento(:save => false) }
        post :create, :metodo_de_pagamento => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested metodo_de_pagamento" do
        MetodoDePagamento.stub(:find).with("37") { mock_metodo_de_pagamento }
        mock_metodo_de_pagamento.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :metodo_de_pagamento => {'these' => 'params'}
      end

      it "assigns the requested metodo_de_pagamento as @metodo_de_pagamento" do
        MetodoDePagamento.stub(:find) { mock_metodo_de_pagamento(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:metodo_de_pagamento).should be(mock_metodo_de_pagamento)
      end

      it "redirects to the metodo_de_pagamento" do
        MetodoDePagamento.stub(:find) { mock_metodo_de_pagamento(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(metodo_de_pagamento_url(mock_metodo_de_pagamento))
      end
    end

    describe "with invalid params" do
      it "assigns the metodo_de_pagamento as @metodo_de_pagamento" do
        MetodoDePagamento.stub(:find) { mock_metodo_de_pagamento(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:metodo_de_pagamento).should be(mock_metodo_de_pagamento)
      end

      it "re-renders the 'edit' template" do
        MetodoDePagamento.stub(:find) { mock_metodo_de_pagamento(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested metodo_de_pagamento" do
      MetodoDePagamento.stub(:find).with("37") { mock_metodo_de_pagamento }
      mock_metodo_de_pagamento.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the metodo_de_pagamentos list" do
      MetodoDePagamento.stub(:find) { mock_metodo_de_pagamento }
      delete :destroy, :id => "1"
      response.should redirect_to(metodo_de_pagamentos_url)
    end
  end

end
