require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PagamentosController do

  def mock_pagamento(stubs={})
    @mock_pagamento ||= mock_model(Pagamento, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all pagamentos as @pagamentos" do
      Pagamento.stub(:all) { [mock_pagamento] }
      get :index
      assigns(:pagamentos).should eq([mock_pagamento])
    end
  end

  describe "GET show" do
    it "assigns the requested pagamento as @pagamento" do
      Pagamento.stub(:find).with("37") { mock_pagamento }
      get :show, :id => "37"
      assigns(:pagamento).should be(mock_pagamento)
    end
  end

  describe "GET new" do
    it "assigns a new pagamento as @pagamento" do
      Pagamento.stub(:new) { mock_pagamento }
      get :new
      assigns(:pagamento).should be(mock_pagamento)
    end
  end

  describe "GET edit" do
    it "assigns the requested pagamento as @pagamento" do
      Pagamento.stub(:find).with("37") { mock_pagamento }
      get :edit, :id => "37"
      assigns(:pagamento).should be(mock_pagamento)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created pagamento as @pagamento" do
        Pagamento.stub(:new).with({'these' => 'params'}) { mock_pagamento(:save => true) }
        post :create, :pagamento => {'these' => 'params'}
        assigns(:pagamento).should be(mock_pagamento)
      end

      it "redirects to the created pagamento" do
        Pagamento.stub(:new) { mock_pagamento(:save => true) }
        post :create, :pagamento => {}
        response.should redirect_to(pagamento_url(mock_pagamento))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pagamento as @pagamento" do
        Pagamento.stub(:new).with({'these' => 'params'}) { mock_pagamento(:save => false) }
        post :create, :pagamento => {'these' => 'params'}
        assigns(:pagamento).should be(mock_pagamento)
      end

      it "re-renders the 'new' template" do
        Pagamento.stub(:new) { mock_pagamento(:save => false) }
        post :create, :pagamento => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pagamento" do
        Pagamento.stub(:find).with("37") { mock_pagamento }
        mock_pagamento.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :pagamento => {'these' => 'params'}
      end

      it "assigns the requested pagamento as @pagamento" do
        Pagamento.stub(:find) { mock_pagamento(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:pagamento).should be(mock_pagamento)
      end

      it "redirects to the pagamento" do
        Pagamento.stub(:find) { mock_pagamento(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(pagamento_url(mock_pagamento))
      end
    end

    describe "with invalid params" do
      it "assigns the pagamento as @pagamento" do
        Pagamento.stub(:find) { mock_pagamento(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:pagamento).should be(mock_pagamento)
      end

      it "re-renders the 'edit' template" do
        Pagamento.stub(:find) { mock_pagamento(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pagamento" do
      Pagamento.stub(:find).with("37") { mock_pagamento }
      mock_pagamento.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the pagamentos list" do
      Pagamento.stub(:find) { mock_pagamento }
      delete :destroy, :id => "1"
      response.should redirect_to(pagamentos_url)
    end
  end

end
