require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PayamentsController do

  def mock_payament(stubs={})
    @mock_payament ||= mock_model(Payament, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all payaments as @payaments" do
      Payament.stub(:all) { [mock_payament] }
      get :index
      assigns(:payaments).should eq([mock_payament])
    end
  end

  describe "GET show" do
    it "assigns the requested payament as @payament" do
      Payament.stub(:find).with("37") { mock_payament }
      get :show, :id => "37"
      assigns(:payament).should be(mock_payament)
    end
  end

  describe "GET new" do
    it "assigns a new payament as @payament" do
      Payament.stub(:new) { mock_payament }
      get :new
      assigns(:payament).should be(mock_payament)
    end
  end

  describe "GET edit" do
    it "assigns the requested payament as @payament" do
      Payament.stub(:find).with("37") { mock_payament }
      get :edit, :id => "37"
      assigns(:payament).should be(mock_payament)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created payament as @payament" do
        Payament.stub(:new).with({'these' => 'params'}) { mock_payament(:save => true) }
        post :create, :payament => {'these' => 'params'}
        assigns(:payament).should be(mock_payament)
      end

      it "redirects to the created payament" do
        Payament.stub(:new) { mock_payament(:save => true) }
        post :create, :payament => {}
        response.should redirect_to(payament_url(mock_payament))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved payament as @payament" do
        Payament.stub(:new).with({'these' => 'params'}) { mock_payament(:save => false) }
        post :create, :payament => {'these' => 'params'}
        assigns(:payament).should be(mock_payament)
      end

      it "re-renders the 'new' template" do
        Payament.stub(:new) { mock_payament(:save => false) }
        post :create, :payament => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested payament" do
        Payament.stub(:find).with("37") { mock_payament }
        mock_payament.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :payament => {'these' => 'params'}
      end

      it "assigns the requested payament as @payament" do
        Payament.stub(:find) { mock_payament(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:payament).should be(mock_payament)
      end

      it "redirects to the payament" do
        Payament.stub(:find) { mock_payament(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(payament_url(mock_payament))
      end
    end

    describe "with invalid params" do
      it "assigns the payament as @payament" do
        Payament.stub(:find) { mock_payament(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:payament).should be(mock_payament)
      end

      it "re-renders the 'edit' template" do
        Payament.stub(:find) { mock_payament(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested payament" do
      Payament.stub(:find).with("37") { mock_payament }
      mock_payament.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the payaments list" do
      Payament.stub(:find) { mock_payament }
      delete :destroy, :id => "1"
      response.should redirect_to(payaments_url)
    end
  end

end
