require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PayamentMethodsController do

  def mock_payament_method(stubs={})
    @mock_payament_method ||= mock_model(PayamentMethod, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all payament_methods as @payament_methods" do
      PayamentMethod.stub(:all) { [mock_payament_method] }
      get :index
      assigns(:payament_methods).should eq([mock_payament_method])
    end
  end

  describe "GET show" do
    it "assigns the requested payament_method as @payament_method" do
      PayamentMethod.stub(:find).with("37") { mock_payament_method }
      get :show, :id => "37"
      assigns(:payament_method).should be(mock_payament_method)
    end
  end

  describe "GET new" do
    it "assigns a new payament_method as @payament_method" do
      PayamentMethod.stub(:new) { mock_payament_method }
      get :new
      assigns(:payament_method).should be(mock_payament_method)
    end
  end

  describe "GET edit" do
    it "assigns the requested payament_method as @payament_method" do
      PayamentMethod.stub(:find).with("37") { mock_payament_method }
      get :edit, :id => "37"
      assigns(:payament_method).should be(mock_payament_method)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created payament_method as @payament_method" do
        PayamentMethod.stub(:new).with({'these' => 'params'}) { mock_payament_method(:save => true) }
        post :create, :payament_method => {'these' => 'params'}
        assigns(:payament_method).should be(mock_payament_method)
      end

      it "redirects to the created payament_method" do
        PayamentMethod.stub(:new) { mock_payament_method(:save => true) }
        post :create, :payament_method => {}
        response.should redirect_to(payament_method_url(mock_payament_method))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved payament_method as @payament_method" do
        PayamentMethod.stub(:new).with({'these' => 'params'}) { mock_payament_method(:save => false) }
        post :create, :payament_method => {'these' => 'params'}
        assigns(:payament_method).should be(mock_payament_method)
      end

      it "re-renders the 'new' template" do
        PayamentMethod.stub(:new) { mock_payament_method(:save => false) }
        post :create, :payament_method => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested payament_method" do
        PayamentMethod.stub(:find).with("37") { mock_payament_method }
        mock_payament_method.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :payament_method => {'these' => 'params'}
      end

      it "assigns the requested payament_method as @payament_method" do
        PayamentMethod.stub(:find) { mock_payament_method(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:payament_method).should be(mock_payament_method)
      end

      it "redirects to the payament_method" do
        PayamentMethod.stub(:find) { mock_payament_method(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(payament_method_url(mock_payament_method))
      end
    end

    describe "with invalid params" do
      it "assigns the payament_method as @payament_method" do
        PayamentMethod.stub(:find) { mock_payament_method(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:payament_method).should be(mock_payament_method)
      end

      it "re-renders the 'edit' template" do
        PayamentMethod.stub(:find) { mock_payament_method(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested payament_method" do
      PayamentMethod.stub(:find).with("37") { mock_payament_method }
      mock_payament_method.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the payament_methods list" do
      PayamentMethod.stub(:find) { mock_payament_method }
      delete :destroy, :id => "1"
      response.should redirect_to(payament_methods_url)
    end
  end

end
