require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PayamentTypesController do

  def mock_payament_type(stubs={})
    @mock_payament_type ||= mock_model(PayamentType, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all payament_types as @payament_types" do
      PayamentType.stub(:all) { [mock_payament_type] }
      get :index
      assigns(:payament_types).should eq([mock_payament_type])
    end
  end

  describe "GET show" do
    it "assigns the requested payament_type as @payament_type" do
      PayamentType.stub(:find).with("37") { mock_payament_type }
      get :show, :id => "37"
      assigns(:payament_type).should be(mock_payament_type)
    end
  end

  describe "GET new" do
    it "assigns a new payament_type as @payament_type" do
      PayamentType.stub(:new) { mock_payament_type }
      get :new
      assigns(:payament_type).should be(mock_payament_type)
    end
  end

  describe "GET edit" do
    it "assigns the requested payament_type as @payament_type" do
      PayamentType.stub(:find).with("37") { mock_payament_type }
      get :edit, :id => "37"
      assigns(:payament_type).should be(mock_payament_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created payament_type as @payament_type" do
        PayamentType.stub(:new).with({'these' => 'params'}) { mock_payament_type(:save => true) }
        post :create, :payament_type => {'these' => 'params'}
        assigns(:payament_type).should be(mock_payament_type)
      end

      it "redirects to the created payament_type" do
        PayamentType.stub(:new) { mock_payament_type(:save => true) }
        post :create, :payament_type => {}
        response.should redirect_to(payament_type_url(mock_payament_type))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved payament_type as @payament_type" do
        PayamentType.stub(:new).with({'these' => 'params'}) { mock_payament_type(:save => false) }
        post :create, :payament_type => {'these' => 'params'}
        assigns(:payament_type).should be(mock_payament_type)
      end

      it "re-renders the 'new' template" do
        PayamentType.stub(:new) { mock_payament_type(:save => false) }
        post :create, :payament_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested payament_type" do
        PayamentType.stub(:find).with("37") { mock_payament_type }
        mock_payament_type.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :payament_type => {'these' => 'params'}
      end

      it "assigns the requested payament_type as @payament_type" do
        PayamentType.stub(:find) { mock_payament_type(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:payament_type).should be(mock_payament_type)
      end

      it "redirects to the payament_type" do
        PayamentType.stub(:find) { mock_payament_type(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(payament_type_url(mock_payament_type))
      end
    end

    describe "with invalid params" do
      it "assigns the payament_type as @payament_type" do
        PayamentType.stub(:find) { mock_payament_type(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:payament_type).should be(mock_payament_type)
      end

      it "re-renders the 'edit' template" do
        PayamentType.stub(:find) { mock_payament_type(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested payament_type" do
      PayamentType.stub(:find).with("37") { mock_payament_type }
      mock_payament_type.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the payament_types list" do
      PayamentType.stub(:find) { mock_payament_type }
      delete :destroy, :id => "1"
      response.should redirect_to(payament_types_url)
    end
  end

end
