require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe RecebimentosController do

  def mock_recebimento(stubs={})
    @mock_recebimento ||= mock_model(Recebimento, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all recebimentos as @recebimentos" do
      Recebimento.stub(:all) { [mock_recebimento] }
      get :index
      assigns(:recebimentos).should eq([mock_recebimento])
    end
  end

  describe "GET show" do
    it "assigns the requested recebimento as @recebimento" do
      Recebimento.stub(:find).with("37") { mock_recebimento }
      get :show, :id => "37"
      assigns(:recebimento).should be(mock_recebimento)
    end
  end

  describe "GET new" do
    it "assigns a new recebimento as @recebimento" do
      Recebimento.stub(:new) { mock_recebimento }
      get :new
      assigns(:recebimento).should be(mock_recebimento)
    end
  end

  describe "GET edit" do
    it "assigns the requested recebimento as @recebimento" do
      Recebimento.stub(:find).with("37") { mock_recebimento }
      get :edit, :id => "37"
      assigns(:recebimento).should be(mock_recebimento)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created recebimento as @recebimento" do
        Recebimento.stub(:new).with({'these' => 'params'}) { mock_recebimento(:save => true) }
        post :create, :recebimento => {'these' => 'params'}
        assigns(:recebimento).should be(mock_recebimento)
      end

      it "redirects to the created recebimento" do
        Recebimento.stub(:new) { mock_recebimento(:save => true) }
        post :create, :recebimento => {}
        response.should redirect_to(recebimento_url(mock_recebimento))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recebimento as @recebimento" do
        Recebimento.stub(:new).with({'these' => 'params'}) { mock_recebimento(:save => false) }
        post :create, :recebimento => {'these' => 'params'}
        assigns(:recebimento).should be(mock_recebimento)
      end

      it "re-renders the 'new' template" do
        Recebimento.stub(:new) { mock_recebimento(:save => false) }
        post :create, :recebimento => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recebimento" do
        Recebimento.stub(:find).with("37") { mock_recebimento }
        mock_recebimento.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :recebimento => {'these' => 'params'}
      end

      it "assigns the requested recebimento as @recebimento" do
        Recebimento.stub(:find) { mock_recebimento(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:recebimento).should be(mock_recebimento)
      end

      it "redirects to the recebimento" do
        Recebimento.stub(:find) { mock_recebimento(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(recebimento_url(mock_recebimento))
      end
    end

    describe "with invalid params" do
      it "assigns the recebimento as @recebimento" do
        Recebimento.stub(:find) { mock_recebimento(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:recebimento).should be(mock_recebimento)
      end

      it "re-renders the 'edit' template" do
        Recebimento.stub(:find) { mock_recebimento(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recebimento" do
      Recebimento.stub(:find).with("37") { mock_recebimento }
      mock_recebimento.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the recebimentos list" do
      Recebimento.stub(:find) { mock_recebimento }
      delete :destroy, :id => "1"
      response.should redirect_to(recebimentos_url)
    end
  end

end
