require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TipoDoPagamentosController do

  def mock_tipo_do_pagamento(stubs={})
    @mock_tipo_do_pagamento ||= mock_model(TipoDoPagamento, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all tipo_do_pagamentos as @tipo_do_pagamentos" do
      TipoDoPagamento.stub(:all) { [mock_tipo_do_pagamento] }
      get :index
      assigns(:tipo_do_pagamentos).should eq([mock_tipo_do_pagamento])
    end
  end

  describe "GET show" do
    it "assigns the requested tipo_do_pagamento as @tipo_do_pagamento" do
      TipoDoPagamento.stub(:find).with("37") { mock_tipo_do_pagamento }
      get :show, :id => "37"
      assigns(:tipo_do_pagamento).should be(mock_tipo_do_pagamento)
    end
  end

  describe "GET new" do
    it "assigns a new tipo_do_pagamento as @tipo_do_pagamento" do
      TipoDoPagamento.stub(:new) { mock_tipo_do_pagamento }
      get :new
      assigns(:tipo_do_pagamento).should be(mock_tipo_do_pagamento)
    end
  end

  describe "GET edit" do
    it "assigns the requested tipo_do_pagamento as @tipo_do_pagamento" do
      TipoDoPagamento.stub(:find).with("37") { mock_tipo_do_pagamento }
      get :edit, :id => "37"
      assigns(:tipo_do_pagamento).should be(mock_tipo_do_pagamento)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created tipo_do_pagamento as @tipo_do_pagamento" do
        TipoDoPagamento.stub(:new).with({'these' => 'params'}) { mock_tipo_do_pagamento(:save => true) }
        post :create, :tipo_do_pagamento => {'these' => 'params'}
        assigns(:tipo_do_pagamento).should be(mock_tipo_do_pagamento)
      end

      it "redirects to the created tipo_do_pagamento" do
        TipoDoPagamento.stub(:new) { mock_tipo_do_pagamento(:save => true) }
        post :create, :tipo_do_pagamento => {}
        response.should redirect_to(tipo_do_pagamento_url(mock_tipo_do_pagamento))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tipo_do_pagamento as @tipo_do_pagamento" do
        TipoDoPagamento.stub(:new).with({'these' => 'params'}) { mock_tipo_do_pagamento(:save => false) }
        post :create, :tipo_do_pagamento => {'these' => 'params'}
        assigns(:tipo_do_pagamento).should be(mock_tipo_do_pagamento)
      end

      it "re-renders the 'new' template" do
        TipoDoPagamento.stub(:new) { mock_tipo_do_pagamento(:save => false) }
        post :create, :tipo_do_pagamento => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tipo_do_pagamento" do
        TipoDoPagamento.stub(:find).with("37") { mock_tipo_do_pagamento }
        mock_tipo_do_pagamento.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :tipo_do_pagamento => {'these' => 'params'}
      end

      it "assigns the requested tipo_do_pagamento as @tipo_do_pagamento" do
        TipoDoPagamento.stub(:find) { mock_tipo_do_pagamento(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:tipo_do_pagamento).should be(mock_tipo_do_pagamento)
      end

      it "redirects to the tipo_do_pagamento" do
        TipoDoPagamento.stub(:find) { mock_tipo_do_pagamento(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(tipo_do_pagamento_url(mock_tipo_do_pagamento))
      end
    end

    describe "with invalid params" do
      it "assigns the tipo_do_pagamento as @tipo_do_pagamento" do
        TipoDoPagamento.stub(:find) { mock_tipo_do_pagamento(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:tipo_do_pagamento).should be(mock_tipo_do_pagamento)
      end

      it "re-renders the 'edit' template" do
        TipoDoPagamento.stub(:find) { mock_tipo_do_pagamento(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tipo_do_pagamento" do
      TipoDoPagamento.stub(:find).with("37") { mock_tipo_do_pagamento }
      mock_tipo_do_pagamento.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the tipo_do_pagamentos list" do
      TipoDoPagamento.stub(:find) { mock_tipo_do_pagamento }
      delete :destroy, :id => "1"
      response.should redirect_to(tipo_do_pagamentos_url)
    end
  end

end
